namespace Heyiwei2
{
    [default_interface]
    runtimeclass AddDormForm : Microsoft.UI.Xaml.Controls.UserControl
    {
        AddDormForm();
        Int32 Region{ get; };
        Int32 BuildingNumber{ get; };
        Int32 FloorNumber{ get; };
        String DormNumber{ get; };
    }
}
