namespace Heyiwei2
{
    [default_interface]
    runtimeclass EditRecordForm : Microsoft.UI.Xaml.Controls.UserControl
    {
        EditRecordForm();

        Windows.Foundation.Collections.IObservableVector<Int32> Years{ get; };
        Windows.Foundation.Collections.IObservableVector<Int32> Months{ get; };
    }
}
