namespace Heyiwei2
{
    [default_interface]
    runtimeclass EditDormForm : Microsoft.UI.Xaml.Controls.UserControl
    {
        EditDormForm();

        Windows.Foundation.Collections.IObservableVector<Int32> Years{ get; };
        Windows.Foundation.Collections.IObservableVector<Int32> Months{ get; };
    }
}
