
namespace Heyiwei2.Models
{
	[bindable]
	[default_interface]
	runtimeclass WaterRecord
	{
		WaterRecord();
		Int32 Year;
		Int32 Month;
		Double Usage;
		Double Cost;
		Boolean HasPaid;
	};

	[bindable]
	[default_interface]
	runtimeclass Student
	{
		Student();
		String Name;
		String StudentId;
	};

	[bindable]
	[default_interface]
	runtimeclass DormInfo : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		DormInfo();
		Int32 Region;
		Int32 BuildingNumber;
		Int32 Floor;
		Int32 RoomNumber;
		String ToString{ get; };

		Int32 StartDateYear;
		Int32 StartDateMonth;
	};

	[bindable]
	[default_interface]
	runtimeclass Dorm : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		Dorm();
		Windows.Foundation.Collections.IObservableVector<Object> Students;
		Windows.Foundation.Collections.IObservableVector<Object> Records;
		String DormId{ get; };
		DormInfo Info;
	};

	[default_interface]
	runtimeclass Result
	{
		Result();
		Result(Boolean success, String message);
		Boolean Success;
		String Message;
	}
}